// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6pqC6-8QA_JS3ED4VNpLpY16unW76wnE',
    appId: '1:191460954059:web:1bf7f9c93111f9d71f304e',
    messagingSenderId: '191460954059',
    projectId: 'smart-pantry-system-e3874',
    authDomain: 'smart-pantry-system-e3874.firebaseapp.com',
    databaseURL: 'https://smart-pantry-system-e3874-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-pantry-system-e3874.firebasestorage.app',
    measurementId: 'G-1NDM9WCVKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd0XpfOGP9A7fL9vKD4Kf0uhcVqPLFdAg',
    appId: '1:191460954059:android:888b28da048468221f304e',
    messagingSenderId: '191460954059',
    projectId: 'smart-pantry-system-e3874',
    databaseURL: 'https://smart-pantry-system-e3874-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-pantry-system-e3874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL7KMLY8_-smNhY7M0KZttrRlJIg1brTE',
    appId: '1:191460954059:ios:2952a86e0b42c9b81f304e',
    messagingSenderId: '191460954059',
    projectId: 'smart-pantry-system-e3874',
    databaseURL: 'https://smart-pantry-system-e3874-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-pantry-system-e3874.firebasestorage.app',
    iosBundleId: 'com.example.smartPantry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL7KMLY8_-smNhY7M0KZttrRlJIg1brTE',
    appId: '1:191460954059:ios:2952a86e0b42c9b81f304e',
    messagingSenderId: '191460954059',
    projectId: 'smart-pantry-system-e3874',
    databaseURL: 'https://smart-pantry-system-e3874-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-pantry-system-e3874.firebasestorage.app',
    iosBundleId: 'com.example.smartPantry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6pqC6-8QA_JS3ED4VNpLpY16unW76wnE',
    appId: '1:191460954059:web:95e103c4fc1afeaf1f304e',
    messagingSenderId: '191460954059',
    projectId: 'smart-pantry-system-e3874',
    authDomain: 'smart-pantry-system-e3874.firebaseapp.com',
    databaseURL: 'https://smart-pantry-system-e3874-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-pantry-system-e3874.firebasestorage.app',
    measurementId: 'G-K8Z35SYLKX',
  );
}
